language: java
jdk:
  - openjdk8
cache:
  directories:
    - .autoconf
    - "$HOME/.m2"
before_install:
  - export LAUNCHER_MISSIONCONTROL_OPENSHIFT_CLUSTERS_FILE=$TRAVIS_BUILD_DIR/clusters.yaml
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Ddownload.cache.skip -B -V
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then mvn test -B -V; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ];  then mvn test failsafe:integration-test failsafe:verify -Pit -B -V; fi'
notifications:
  slack: obsidian-toaster:gdvv4335GhJm7iEarR6e9aJr
